name: zendo_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: ^5.4.0+1
  device_preview: ^1.0.0
  wc_form_validators: ^1.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  font_awesome_flutter: 10.1.0
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  shimmer_animation: 2.1.0+1
  path_provider: 2.0.10
  dio: 4.0.6
  permission_handler: 9.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  test: ^1.19.5
  mockito: ^5.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true

